name: Build Android

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: '22.x'
        cache: npm

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'jetbrains'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v4

    - name: Build tiSensible
      run: |
        npm ci
        npm run build
        npx cap sync
        cd android
        ./gradlew assemble
        cd ..
        mv android/app/build/outputs/apk/release/app-release-unsigned.apk .

    - name: Sign tiSensible
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        BUILD_TOOL_DIR=$(ls -d $ANDROID_HOME/build-tools/* | tail -1)
        echo "$KEYSTORE_BASE64" | base64 --decode > keystore.jks
        $BUILD_TOOL_DIR/zipalign -v -p 4 app-release-unsigned.apk app-release-unsigned-aligned.apk
        $BUILD_TOOL_DIR/apksigner sign \
          --ks keystore.jks \
          --ks-key-alias "$KEY_ALIAS" \
          --ks-pass pass:"$KEY_PASSWORD" \
          --key-pass pass:"$KEY_PASSWORD" \
          --out app-release-signed.apk \
          app-release-unsigned-aligned.apk
        rm keystore.jks

    - name: Upload build outputs
      uses: actions/upload-artifact@v7
      with:
        name: app-release-signed.apk
        path: app-release-signed.apk
        retention-days: 10
